checks:
    python:
        code_rating: true
        duplicate_code: true

filter:
    excluded_paths:
        - "Server/app_v1/views/static/*"
        - "Server/app_v1/views/templates/*"
        - "Server/app_v2/views/static/*"
        - "Server/app_v2/views/templates/*"
