build:
    tests:
        override:
            -
                command: 'coverage run --source=Server/app Server/run_test.py'
                coverage:
                    file: '.coverage'
                    config_file: '.coveragerc'
                    format: 'py-cc'

checks:
    python:
        code_rating: true
        duplicate_code: true

filter:
    excluded_paths:
        - "Server/app/static/*"
        - "Server/app/templates/*"
