checks:
    python:
        code_rating: true
        duplicate_code: true

filter:
    excluded_paths:
        - "Server/app_v1/static/*"
        - "Server/app_v1/templates/*"
        - "Server/app_v2/static/*"
        - "Server/app_v2/templates/*"
